### ISSUE TITLE
Does not work on Mac

### ISSUE THREAD

**Issue by bknarendra** [cwoodall/doppler-gestures-py#18]
When I run this on my mac. It throws this exception.

➜  doppler-gestures-py git:(master) ./bin/doppler-gestures.py --tone 20000 --window 500 --channels 2
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on **THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC**() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on **THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC**() to debug.

**Comment by cwoodall** [comment]
Thanks for the feedback. I may get around to it I think I have a mac accessible to me. For reference I developed this on Ubuntu 14.04 pretty much exclusively.
